### ISSUE TITLE
Keep existing function name in unmapped source files

### ISSUE THREAD

**Issue by slaneyrw** [novocaine/sourcemapped-stacktrace#10]
When a source map is not found for a url then can we keep the existing function name from the stack trace line instead of replacing with (unknown)

For example, a Jasmine unit test fail generates:

`Error: Expected Function to be true.

    at stack (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1577:17)
    at buildExpectationResult (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1547:14)
    at Spec.Env.expectationResultFactory (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:638:18)
    at Spec.addExpectationResult (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:330:34)
    at Expectation.addExpectationResult (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:588:21)
    at Expectation.toBe (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1501:12)
    at Object.<anonymous> (https://localhost:44364/ScriptTests/Specs/knockout-utils.js:49:28)
    at attemptSync (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1886:24)
    at QueueRunner.run (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1874:9)
    at QueueRunner.execute (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1859:10)`

This is transformed into 

`Expected Function to be true.

    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1577:17)
    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1547:14)
    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:638:18)
    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:330:34)
    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:588:21)
    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1501:12)
    at (unknown) (knockout-utils.ts:71:23)
    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1886:24)
    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1874:9)
    at (unknown) (https://localhost:44364/ScriptTests/lib/jasmine/jasmine.js:1859:10)`

jasmine.js doesn't have a source map

**Comment by novocaine** [comment]
Great suggestion. I haven't had time to look at it myself unfortunately..

**Comment by novocaine** [comment]
fixed by #11
